---
title: "Case Study - Cyclistic"
output: 
  html_document:
    theme: cosmo
---

<style type="text/css">
.title {
  display: none;
}

#getting-started img {
  margin-right: 10px;
}

</style>

<div class="row" style="padding-top: 30px;">
<div class="col-sm-6">

# **Case Study: How Does a Bike-Share Navigate Speedy Success**


## **Company: Cyclistic**


#### **About the Company:**

+ 5,824 bicycles and 692 docking stations
+ The majority of riders opt for traditional bikes
+ 8% of riders use the assistive options.
+ Cyclistic users are more likely to ride for leisure
+ 30% use them to commute to work each day.


#### **Main Questions:**

1. How do annual members and casual riders use Cyclistic bikes differently?

2. What are the implications for maximizing annual members derived from the difference between annual members and casual riders? 

#### **Business Task:**

+ What measures do persuade **casual riders** into signing up for a annual membership.


+ **Reliable:** Data read from Bike Computer
+ **Original:** First Source Data provided by Cyclistic
+ **Comprehensive:** Clear Data Structure 
+ **Current:** Recent Data from last year

-> Clear descriptive data provided by GPS, Membership information and type of bike. Does not exclude specific data. (collects all data as a whole) Therefore no bias recognized.

#### **Data:**

Columns: 13
Rows: 5,723,532


</div>
<div class="col-sm-6">

### Tools Used:

+ RStudio
+ Tableau
+ GithubPages

</a>
</div>
