<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Detailed Report</title>

<script src="site_libs/header-attrs-2.14/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Case Study - Cyclistic</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Detailed-Report.html">Detailed Report</a>
</li>
<li>
  <a href="Links.html">Links</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore"><strong>Detailed Report</strong></h1>

</div>


<div id="load-files-and-packages" class="section level4">
<h4><strong>Load files and packages:</strong></h4>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geosphere)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>data_all <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="at">path =</span> <span class="st">&quot;/Users/jonaslenz/Case Study Cyclistic/Data Sets Used&quot;</span>, <span class="at">pattern =</span> <span class="st">&quot;May2021_to_April2022_Cyclist_Data.csv&quot;</span>, <span class="at">full.names =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lapply</span>(read_csv) <span class="sc">%&gt;%</span>                        </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  bind_rows</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>data_all_before_mapulation <span class="ot">&lt;-</span> data_all</span></code></pre></div>
</div>
<div id="data-cleaning-with-r" class="section level2">
<h2><strong>1. Data Cleaning with R</strong></h2>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#order Data before cleaning by started at</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>data_all <span class="ot">&lt;-</span> data_all[<span class="fu">order</span>(data_all<span class="sc">$</span>started_at),]</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_all)</span></code></pre></div>
<pre><code>## Rows: 5,723,532
## Columns: 14
## $ ...1               &lt;dbl&gt; 39495, 273781, 34832, 16811, 131422, 9916, 51657, 2…
## $ ride_id            &lt;chr&gt; &quot;0DA46DD62F111D09&quot;, &quot;FF009F812ADAFB3E&quot;, &quot;623C22F8DE…
## $ rideable_type      &lt;chr&gt; &quot;electric_bike&quot;, &quot;classic_bike&quot;, &quot;electric_bike&quot;, &quot;…
## $ started_at         &lt;dttm&gt; 2021-04-01 00:03:18, 2021-04-01 00:03:47, 2021-04-…
## $ ended_at           &lt;dttm&gt; 2021-04-01 00:30:59, 2021-04-01 00:23:26, 2021-04-…
## $ start_station_name &lt;chr&gt; &quot;Western Ave &amp; Howard St&quot;, &quot;LaSalle St &amp; Illinois S…
## $ start_station_id   &lt;chr&gt; &quot;527&quot;, &quot;13430&quot;, NA, &quot;TA1307000131&quot;, &quot;KA1504000133&quot;,…
## $ end_station_name   &lt;chr&gt; &quot;Campbell Ave &amp; Fullerton Ave&quot;, &quot;Wentworth Ave &amp; 24…
## $ end_station_id     &lt;chr&gt; &quot;15648&quot;, &quot;TA1308000026&quot;, NA, &quot;13045&quot;, &quot;TA1309000025…
## $ start_lat          &lt;dbl&gt; 42.01888, 41.89076, 41.72000, 41.88688, 41.90236, 4…
## $ start_lng          &lt;dbl&gt; -87.69008, -87.63170, -87.62000, -87.62603, -87.627…
## $ end_lat            &lt;dbl&gt; 41.92465, 41.85008, 41.70000, 41.89399, 41.94366, 4…
## $ end_lng            &lt;dbl&gt; -87.68929, -87.63214, -87.65000, -87.62932, -87.648…
## $ member_casual      &lt;chr&gt; &quot;member&quot;, &quot;member&quot;, &quot;member&quot;, &quot;member&quot;, &quot;member&quot;, &quot;…</code></pre>
<ul>
<li>Deleting NA entries:</li>
</ul>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>data_all <span class="ot">&lt;-</span> <span class="fu">drop_na</span>(data_all)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_all)</span></code></pre></div>
<pre><code>## Rows: 4,641,395
## Columns: 14
## $ ...1               &lt;dbl&gt; 39495, 273781, 16811, 131422, 9916, 51657, 251943, …
## $ ride_id            &lt;chr&gt; &quot;0DA46DD62F111D09&quot;, &quot;FF009F812ADAFB3E&quot;, &quot;8089677A94…
## $ rideable_type      &lt;chr&gt; &quot;electric_bike&quot;, &quot;classic_bike&quot;, &quot;classic_bike&quot;, &quot;e…
## $ started_at         &lt;dttm&gt; 2021-04-01 00:03:18, 2021-04-01 00:03:47, 2021-04-…
## $ ended_at           &lt;dttm&gt; 2021-04-01 00:30:59, 2021-04-01 00:23:26, 2021-04-…
## $ start_station_name &lt;chr&gt; &quot;Western Ave &amp; Howard St&quot;, &quot;LaSalle St &amp; Illinois S…
## $ start_station_id   &lt;chr&gt; &quot;527&quot;, &quot;13430&quot;, &quot;TA1307000131&quot;, &quot;KA1504000133&quot;, &quot;13…
## $ end_station_name   &lt;chr&gt; &quot;Campbell Ave &amp; Fullerton Ave&quot;, &quot;Wentworth Ave &amp; 24…
## $ end_station_id     &lt;chr&gt; &quot;15648&quot;, &quot;TA1308000026&quot;, &quot;13045&quot;, &quot;TA1309000025&quot;, &quot;…
## $ start_lat          &lt;dbl&gt; 42.01888, 41.89076, 41.88688, 41.90236, 41.97835, 4…
## $ start_lng          &lt;dbl&gt; -87.69008, -87.63170, -87.62603, -87.62783, -87.659…
## $ end_lat            &lt;dbl&gt; 41.92465, 41.85008, 41.89399, 41.94366, 41.96797, 4…
## $ end_lng            &lt;dbl&gt; -87.68929, -87.63214, -87.62932, -87.64884, -87.650…
## $ member_casual      &lt;chr&gt; &quot;member&quot;, &quot;member&quot;, &quot;member&quot;, &quot;member&quot;, &quot;member&quot;, &quot;…</code></pre>
<p>Dropped Rows: <strong>1,082,137</strong> = 5,723,532 - 4,641,395</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># count casuals and members before and after cleaning</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(data_all, <span class="at">vars =</span> member_casual)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   vars         n
##   &lt;chr&gt;    &lt;int&gt;
## 1 casual 2044339
## 2 member 2597056</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(data_all_before_mapulation, <span class="at">vars =</span> member_casual)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   vars         n
##   &lt;chr&gt;    &lt;int&gt;
## 1 casual 2546542
## 2 member 3176990</code></pre>
<p>Compared casuals are nearly riding as much as Members in Total. The NA in the data seem random judging from the relative equality in reduction of members and casuals from the Data Frame. Therefore this can be assumed as Random noise and excluded.</p>
<p><br></p>
</div>
<div id="analysis-with-r" class="section level2">
<h2><strong>2. Analysis with R</strong></h2>
<div id="bike-types" class="section level3">
<h3><strong>2.1 Bike Types</strong></h3>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#count casuals and members for each different bike type</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(<span class="fu">filter</span>(data_all, rideable_type<span class="sc">==</span><span class="st">&quot;classic_bike&quot;</span> ), <span class="at">vars =</span> member_casual)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   vars         n
##   &lt;chr&gt;    &lt;int&gt;
## 1 casual 1252609
## 2 member 1989380</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(<span class="fu">filter</span>(data_all, rideable_type<span class="sc">==</span><span class="st">&quot;electric_bike&quot;</span> ), <span class="at">vars =</span> member_casual)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   vars        n
##   &lt;chr&gt;   &lt;int&gt;
## 1 casual 488206
## 2 member 607676</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(<span class="fu">filter</span>(data_all, rideable_type<span class="sc">==</span><span class="st">&quot;docked_bike&quot;</span> ), <span class="at">vars =</span> member_casual)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   vars        n
##   &lt;chr&gt;   &lt;int&gt;
## 1 casual 303524</code></pre>
<ul>
<li>38% of the classic_bikes are used by casual members</li>
<li>44.55% of the electric_bikes are used by casual members</li>
<li>The docked_bikes are only used by casual members</li>
</ul>
<p><br></p>
</div>
<div id="users-per-location-id" class="section level3">
<h3><strong>2.2 Users per Location ID</strong></h3>
<div id="highest-count-of-riders-per-type" class="section level4">
<h4><strong>2.2.1 Highest Count of riders per type:</strong></h4>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get the highest counts of each membership type and order them from highest to lowest</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>count_station_id_member <span class="ot">&lt;-</span> <span class="fu">count</span>(<span class="fu">group_by</span>(data_all,start_station_id), <span class="at">vars=</span>member_casual)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>count_station_id_member <span class="ot">&lt;-</span> count_station_id_member[<span class="fu">order</span>(count_station_id_member<span class="sc">$</span>n, <span class="at">decreasing =</span> <span class="cn">TRUE</span>), ]</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(count_station_id_member)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
## # Groups:   start_station_id [6]
##   start_station_id vars       n
##   &lt;chr&gt;            &lt;chr&gt;  &lt;int&gt;
## 1 13022            casual 65428
## 2 13300            casual 34230
## 3 13008            casual 31875
## 4 LF-005           casual 28617
## 5 13042            casual 28543
## 6 KA1503000043     member 24186</code></pre>
<p><br></p>
</div>
<div id="highest-count-of-riders-in-total" class="section level4">
<h4><strong>2.2.2 Highest Count of riders in Total:</strong></h4>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get the highest count of total riders and order them from highest to lowest</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>count_start_station_id <span class="ot">&lt;-</span> <span class="fu">count</span>(<span class="fu">group_by</span>(data_all,start_station_id), <span class="at">vars=</span>start_station_id)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>count_start_station_id <span class="ot">&lt;-</span> count_start_station_id[<span class="fu">order</span>(count_start_station_id<span class="sc">$</span>n, <span class="at">decreasing =</span> <span class="cn">TRUE</span>), ]</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(count_start_station_id)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
## # Groups:   start_station_id [6]
##   start_station_id vars             n
##   &lt;chr&gt;            &lt;chr&gt;        &lt;int&gt;
## 1 13022            13022        81546
## 2 LF-005           LF-005       46327
## 3 13300            13300        44181
## 4 13042            13042        42627
## 5 TA1308000050     TA1308000050 41982
## 6 13008            13008        40466</code></pre>
<p><br></p>
</div>
<div id="exlude-low-casual-stations" class="section level4">
<h4><strong>2.2.3 Exlude low Casual Stations</strong></h4>
<p><strong>Next steps:</strong></p>
<ul>
<li><p>Merge the 2 Tables and get the total number in order to evaluate the % of casual members per starting station. We do this because we want to know which stations are most successful for acquiring members so we can dive deeper into what reasons are behind that.</p></li>
<li><p>By knowing which stations have the highest rate of casual riders we get to know where our approach to acquire members is most successful of course in relation to the number of total members. That is why all stations below the 75 percentile casual riders are dropped in order to focus on the most important ones.</p></li>
</ul>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Quantile and Mean of Casual_riders for cutting datapoints</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>total_station_casual <span class="ot">&lt;-</span> <span class="fu">merge</span>(count_start_station_id, count_station_id_member, <span class="at">by.x =</span> <span class="dv">1</span>, <span class="at">by.y =</span> <span class="dv">1</span>, <span class="at">all.x =</span> <span class="cn">TRUE</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>total_station_casual <span class="ot">&lt;-</span> total_station_casual[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">2</span>)] <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">riders_total =</span> n.x,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">member_casual =</span> vars.y,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">total_casual =</span> n.y)<span class="sc">%&gt;%</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">perc_member_casual=</span>(total_casual<span class="sc">/</span>riders_total<span class="sc">*</span><span class="dv">100</span>))<span class="sc">%&gt;%</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(. , <span class="sc">-</span>perc_member_casual)<span class="sc">%&gt;%</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(.,member_casual <span class="sc">==</span> <span class="st">&quot;casual&quot;</span>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(total_station_casual<span class="sc">$</span>total_casual)</span></code></pre></div>
<pre><code>## [1] 2416.476</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">quantile</span>(total_station_casual<span class="sc">$</span>total_casual)</span></code></pre></div>
<pre><code>##       0%      25%      50%      75%     100% 
##     1.00    73.00   613.00  3150.75 65428.00</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Highest Frequency of Casual_riders ordered by highest percentage</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>total_station_casual <span class="ot">&lt;-</span><span class="fu">subset</span>(total_station_casual, total_casual <span class="sc">&gt;=</span> <span class="fl">3150.75</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(total_station_casual)<span class="sc">%&gt;%</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(., start_station_id, riders_total, total_casual, perc_member_casual)</span></code></pre></div>
<pre><code>##     start_station_id riders_total total_casual perc_member_casual
## 109            15541        13623        11674           85.69331
## 143            15544        27235        22476           82.52616
## 156            13029         8428         6824           80.96820
## 163            13022        81546        65428           80.23447
## 178            13008        40466        31875           78.76983
## 200            13300        44181        34230           77.47674</code></pre>
<ul>
<li>The dataset now contains <strong>212 Stations</strong>, which are most important for Cyclistic to Act on, in Descending order by the highest proportion of casual riders.</li>
</ul>
<p><strong>Check if not too much Data is excluded :</strong></p>
<p><strong>The Dataframe contains:</strong></p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Sum all casual members after cleaning out 75% of stations</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(total_station_casual<span class="sc">$</span>total_casual)</span></code></pre></div>
<pre><code>## [1] 1645291</code></pre>
<p><strong>1,645,291</strong> out of <strong>2,044,339</strong> casuals from <strong>212</strong> biggest stations of casual riders.</p>
<p><br></p>
</div>
<div id="exlude-low-member-stations" class="section level4">
<h4><strong>2.2.4 Exlude low Member Stations</strong></h4>
<ul>
<li>To get to know Differences between Members and Casuals we reverse the Task and do the same from above to Members</li>
</ul>
<p><strong>Result:</strong></p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Reversed to find Quantile/Mean Members</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>total_station_member <span class="ot">&lt;-</span> <span class="fu">merge</span>(count_start_station_id, count_station_id_member, <span class="at">by.x =</span> <span class="dv">1</span>, <span class="at">by.y =</span> <span class="dv">1</span>, <span class="at">all.x =</span> <span class="cn">TRUE</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>total_station_member <span class="ot">&lt;-</span> total_station_member[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">2</span>)] <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">riders_total =</span> n.x,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">member_casual =</span> vars.y,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">total_member =</span> n.y)<span class="sc">%&gt;%</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">perc_member_casual=</span>(total_member<span class="sc">/</span>riders_total<span class="sc">*</span><span class="dv">100</span>))<span class="sc">%&gt;%</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(. , <span class="sc">-</span>perc_member_casual)<span class="sc">%&gt;%</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(.,member_casual <span class="sc">==</span> <span class="st">&quot;member&quot;</span>)</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(total_station_member<span class="sc">$</span>total_member)</span></code></pre></div>
<pre><code>## [1] 3117.714</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(total_station_member<span class="sc">$</span>total_member)</span></code></pre></div>
<pre><code>##    0%   25%   50%   75%  100% 
##     1    26   821  5211 24186</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Highest frequency of members ordered by highest percentage</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>total_station_member <span class="ot">&lt;-</span><span class="fu">subset</span>(total_station_member, total_member <span class="sc">&gt;=</span> <span class="dv">5211</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(total_station_member)<span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(., start_station_id, riders_total, total_member, perc_member_casual)</span></code></pre></div>
<pre><code>##     start_station_id riders_total total_member perc_member_casual
## 111            13216         9831         8408           85.52538
## 117            13285         6770         5762           85.11078
## 118     TA1309000064         9930         8436           84.95468
## 120            13332        17099        14511           84.86461
## 140     TA1307000130        10852         9004           82.97088
## 147     TA1307000121        10467         8552           81.70440</code></pre>
<ul>
<li>The dataset now contains <strong>209 Stations</strong>, which are most important for Cyclistic to get information on members.</li>
</ul>
<p><br></p>
</div>
</div>
<div id="time" class="section level3">
<h3><strong>2.3 Time</strong></h3>
<div id="mean-riding-time-per-rider" class="section level4">
<h4><strong>2.3.1 Mean Riding-Time per rider</strong></h4>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Mean Time Casual</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>time_data_all <span class="ot">&lt;-</span> data_all<span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">riding_time =</span> <span class="fu">round</span>(<span class="fu">as.vector</span>(ended_at <span class="sc">-</span> started_at)<span class="sc">/</span><span class="dv">60</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>( . ,<span class="sc">-</span>riding_time)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Select View</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">arrange</span>(time_data_all, riding_time)) <span class="sc">%&gt;%</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(., start_station_id, member_casual, riding_time)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##   start_station_id member_casual riding_time
##   &lt;chr&gt;            &lt;chr&gt;               &lt;dbl&gt;
## 1 13128            casual                -56
## 2 13191            member                -54
## 3 13243            member                -54
## 4 TA1309000023     casual                -53
## 5 13191            casual                -53
## 6 RN-              casual                -51</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Select View</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(time_data_all) <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(., start_station_id, member_casual, riding_time)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##   start_station_id member_casual riding_time
##   &lt;chr&gt;            &lt;chr&gt;               &lt;dbl&gt;
## 1 TA1305000011     casual              55944
## 2 13022            casual              55692
## 3 TA1305000035     casual              53922
## 4 KA1503000012     casual              52701
## 5 13085            casual              49107
## 6 TA1307000131     casual              47777</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(time_data_all<span class="sc">$</span>riding_time)</span></code></pre></div>
<pre><code>## [1] 21.35558</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(time_data_all, <span class="fu">aes</span>(<span class="at">x =</span> riding_time)) <span class="sc">+</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">notch=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="Detailed-Report_files/figure-html/Mean%20Time%20Casual-1.png" width="672" /></p>
<ul>
<li><p>On average riders using the Cyclist product are cycling <strong>ca. 21 minutes</strong>.</p></li>
<li><p>The Highest and Lowest Values seem to be non significant <strong>outliers</strong> and we cut them as they do not represent our data. The Min Values especially below zero do not make any sense, but also 1 second riding_time for example is not anything we can expand upon.</p></li>
<li><p>There are a lot of outliers as confirmed by the Boxplot above.</p></li>
</ul>
<p><br></p>
</div>
<div id="cut-1-of-the-bottom-and-top" class="section level4">
<h4><strong>2.3.2 Cut 1% of the bottom and Top</strong></h4>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get Quantiles to cut data</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(time_data_all<span class="sc">$</span>riding_time, <span class="fu">c</span>(.<span class="dv">99</span>))</span></code></pre></div>
<pre><code>## 99% 
## 129</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(time_data_all<span class="sc">$</span>riding_time, <span class="fu">c</span>(.<span class="dv">01</span>))</span></code></pre></div>
<pre><code>## 1% 
##  1</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(time_data_all<span class="sc">$</span>riding_time)</span></code></pre></div>
<pre><code>## [1] 21.35558</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">#remove of Data</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>time_all <span class="ot">&lt;-</span> <span class="fu">subset</span>(time_data_all, riding_time <span class="sc">&gt;=</span> <span class="dv">1</span> <span class="sc">&amp;</span> riding_time <span class="sc">&lt;=</span> <span class="dv">129</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(time_all)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 15
##     ...1 ride_id          rideable_type started_at          ended_at           
##    &lt;dbl&gt; &lt;chr&gt;            &lt;chr&gt;         &lt;dttm&gt;              &lt;dttm&gt;             
## 1 292649 97192AE375753B66 classic_bike  2021-04-02 21:42:12 2021-04-02 23:50:50
## 2  87098 FB83A0F1CA74A5C4 docked_bike   2021-04-03 03:15:46 2021-04-03 05:24:33
## 3 300577 3A7B43070C572A1A docked_bike   2021-04-03 12:45:26 2021-04-03 14:54:10
## 4 310181 0B00938460D56814 docked_bike   2021-04-03 12:46:39 2021-04-03 14:55:38
## 5 266414 9210C254AF169781 classic_bike  2021-04-03 13:47:15 2021-04-03 15:56:27
## 6 282329 7EEE94AFB81836C6 classic_bike  2021-04-03 13:47:44 2021-04-03 15:56:17
## # … with 10 more variables: start_station_name &lt;chr&gt;, start_station_id &lt;chr&gt;,
## #   end_station_name &lt;chr&gt;, end_station_id &lt;chr&gt;, start_lat &lt;dbl&gt;,
## #   start_lng &lt;dbl&gt;, end_lat &lt;dbl&gt;, end_lng &lt;dbl&gt;, member_casual &lt;chr&gt;,
## #   riding_time &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(time_all<span class="sc">$</span>riding_time)</span></code></pre></div>
<pre><code>## [1] 17.46532</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(time_all, <span class="fu">aes</span>(<span class="at">x =</span> riding_time)) <span class="sc">+</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Boxplot Riding_time&quot;</span>)</span></code></pre></div>
<p><img src="Detailed-Report_files/figure-html/remove%20of%20Data-1.png" width="672" /></p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Histogramm riding Time</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(time_all, <span class="fu">aes</span>(<span class="at">x =</span> riding_time)) <span class="sc">+</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Histogramm riding_time&quot;</span>)</span></code></pre></div>
<p><img src="Detailed-Report_files/figure-html/Hist%20riding%20Time-1.png" width="672" /></p>
<ul>
<li><p>By removing outliers the average dropped by <strong>ca. 4 Minutes</strong>.</p></li>
<li><p>Above <strong>40 Minutes</strong> there are still many outliers.</p></li>
<li><p>Histogramm: the most data points are distributed on the left side, but the mean increases due to many small data points at the right side.</p></li>
</ul>
<p><br></p>
</div>
<div id="mean-time-casual-riders" class="section level4">
<h4><strong>2.3.3 Mean time Casual riders</strong></h4>
<ul>
<li>Now we aggregate the data by only displaying casuals first and then members.</li>
</ul>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Casual Time boxplot</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>time_all_casuals <span class="ot">&lt;-</span> <span class="fu">subset</span>(time_all, member_casual <span class="sc">==</span> <span class="st">&quot;casual&quot;</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(time_all_casuals<span class="sc">$</span>riding_time)</span></code></pre></div>
<pre><code>## [1] 23.6062</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(time_all_casuals, <span class="fu">aes</span>(<span class="at">x =</span> riding_time)) <span class="sc">+</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Boxplot Riding_time per Casual&quot;</span>)</span></code></pre></div>
<p><img src="Detailed-Report_files/figure-html/Casual%20Time%20box-1.png" width="672" /></p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Casual Time Histogramm</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(time_all_casuals, <span class="fu">aes</span>(<span class="at">x =</span> riding_time)) <span class="sc">+</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Histogramm Riding_time per Casual&quot;</span>)</span></code></pre></div>
<p><img src="Detailed-Report_files/figure-html/Casual%20Time%20Hist-1.png" width="672" /></p>
<ul>
<li>Casual riders have a really high riding_time. But the most important part is the riding time <strong>1 to 50</strong> minutes contains most of the casual riders.</li>
<li>The mean riding time of casual riders is <strong>ca. 23 Minutes</strong></li>
</ul>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Member Time Boxplot</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>time_all_member <span class="ot">&lt;-</span> <span class="fu">subset</span>(time_all, member_casual <span class="sc">==</span> <span class="st">&quot;member&quot;</span>)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(time_all_member<span class="sc">$</span>riding_time)</span></code></pre></div>
<pre><code>## [1] 12.70632</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(time_all_member, <span class="fu">aes</span>(<span class="at">x =</span> riding_time)) <span class="sc">+</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Boxplot Riding_time per member&quot;</span>)</span></code></pre></div>
<p><img src="Detailed-Report_files/figure-html/Member%20Time%20Box-1.png" width="672" /></p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Member Time Histogramm</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(time_all_member, <span class="fu">aes</span>(<span class="at">x =</span> riding_time)) <span class="sc">+</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Histogramm Riding_time per member&quot;</span>)</span></code></pre></div>
<p><img src="Detailed-Report_files/figure-html/Member%20Time%20Hist-1.png" width="672" /></p>
<ul>
<li>The mean riding time of members is <strong>ca. 13 Minutes</strong></li>
<li>The mean riding_time is higher for Casuals than members by more than <strong>10 minutes</strong>.</li>
<li>The distribution of riding_time is much more Narrow for members. <strong>Confirmed by the Standard Deviation:</strong></li>
</ul>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Standard deviation for casuals riding_time and members riding_time</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(time_all_casuals<span class="sc">$</span>riding_time) </span></code></pre></div>
<pre><code>## [1] 21.99483</code></pre>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(time_all_member<span class="sc">$</span>riding_time)</span></code></pre></div>
<pre><code>## [1] 10.66348</code></pre>
<ul>
<li>Cyclistic should evaluate what makes riders who ride for a mid to long time not use the membership.</li>
</ul>
<p><br></p>
</div>
<div id="regression-casuals-impact-on-riding-time" class="section level4">
<h4><strong>2.3.4 Regression: Casuals impact on riding time</strong></h4>
<ul>
<li><p>Trend of how the % of Casual riders impacts the average riding_time per station</p></li>
<li><p>We take the 212 Stations which have the most casual riders in Percent from <strong>Chapter 2.2.3</strong> :</p></li>
</ul>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co">#creating Df and Linear Model for Trend analysis</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>most_casual_riders <span class="ot">&lt;-</span> total_station_casual<span class="sc">$</span>start_station_id[<span class="dv">1</span><span class="sc">:</span><span class="dv">212</span>]</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>most_casual_perc <span class="ot">&lt;-</span> total_station_casual<span class="sc">$</span>perc_member_casual[<span class="dv">1</span><span class="sc">:</span><span class="dv">212</span>]</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>mean_casual_station <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">nrows =</span> <span class="dv">212</span>)</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>mean_casual_station <span class="ot">&lt;-</span> <span class="fu">cbind</span>(mean_casual_station,<span class="at">start_station_id =</span> <span class="fu">c</span>(most_casual_riders))</span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>mean_casual_station <span class="ot">&lt;-</span> <span class="fu">cbind</span>(mean_casual_station,<span class="at">perc_casual =</span> <span class="fu">c</span>(most_casual_perc))</span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>mean_list <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> most_casual_riders){</span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a>mean_list <span class="ot">&lt;-</span> <span class="fu">append</span>(mean_list, <span class="fu">mean</span>(<span class="fu">subset</span>(time_all, start_station_id <span class="sc">==</span> i)<span class="sc">$</span>riding_time)) </span>
<span id="cb65-14"><a href="#cb65-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb65-15"><a href="#cb65-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-16"><a href="#cb65-16" aria-hidden="true" tabindex="-1"></a>mean_casual_station <span class="ot">&lt;-</span> <span class="fu">cbind</span>(mean_casual_station, <span class="at">mean_riding_time =</span> <span class="fu">c</span>(mean_list))</span>
<span id="cb65-17"><a href="#cb65-17" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(mean_casual_station<span class="sc">$</span>mean_riding_time, mean_casual_station<span class="sc">$</span>perc_casual)</span></code></pre></div>
<pre><code>## [1] 0.814872</code></pre>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mean_casual_station)</span></code></pre></div>
<pre><code>##   nrows start_station_id perc_casual mean_riding_time
## 1   212            15541    85.69331         35.29438
## 2   212            15544    82.52616         29.18788
## 3   212            13029    80.96820         28.87227
## 4   212            13022    80.23447         31.56451
## 5   212            13008    78.76983         32.55147
## 6   212            13300    77.47674         32.66521</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(perc_casual<span class="sc">~</span>mean_riding_time,<span class="at">data=</span>mean_casual_station))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = perc_casual ~ mean_riding_time, data = mean_casual_station)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -23.5625  -3.3720   0.0343   3.8971  18.7569 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      16.09344    1.45204   11.08   &lt;2e-16 ***
## mean_riding_time  1.63341    0.08018   20.37   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.374 on 210 degrees of freedom
## Multiple R-squared:  0.664,  Adjusted R-squared:  0.6624 
## F-statistic:   415 on 1 and 210 DF,  p-value: &lt; 2.2e-16</code></pre>
<ul>
<li><p>A Linear Model like above shows the Positive significant influence of the percentage of casuals on to the mean riding time. It also describes R^2 = <strong>66.4%</strong> of the Riding_Time variable.</p></li>
<li><p><strong>Visualization:</strong></p></li>
</ul>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plotting percentage of casuals vs. riding time</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>trend_casual_time <span class="ot">&lt;-</span><span class="fu">ggplot</span>(mean_casual_station, <span class="fu">aes</span>(<span class="at">x =</span> perc_casual, <span class="at">y =</span> mean_riding_time)) <span class="sc">+</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>( , <span class="at">se=</span><span class="cn">FALSE</span>)</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>trend_casual_time <span class="ot">&lt;-</span> trend_casual_time <span class="sc">+</span> <span class="fu">expand_limits</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">y =</span> <span class="dv">0</span>)</span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>trend_casual_time<span class="ot">&lt;-</span> trend_casual_time <span class="sc">+</span> <span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)) <span class="sc">+</span> <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>))</span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a>trend_casual_time</span></code></pre></div>
<p><img src="Detailed-Report_files/figure-html/Plotting%20percentage%20of%20casuals%20vs.%20riding%20time-1.png" width="672" /></p>
<p><br></p>
</div>
</div>
<div id="distance" class="section level3">
<h3><strong>2.4 Distance</strong></h3>
<div id="distance-and-time" class="section level4">
<h4><strong>2.4.1 Distance and Time</strong></h4>
<ul>
<li><p>We can not examine a distance if the end station does equal the starting station so we rule these points out.</p></li>
<li><p>Our assumption for this chapter has to be that the traveled distance to the end point is a straight line which is not realistic (on average the result should still show a certain trend).</p></li>
</ul>
<p>First we examine the time it takes for a casual to ride a certain distance in comparison to a member. <strong>(Dataframe from chapter 2.3.2)</strong></p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create Distance Df and attach to location df</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>time_distance <span class="ot">&lt;-</span> time_all <span class="sc">%&gt;%</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(., start_station_id <span class="sc">!=</span> end_station_id) </span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>time_distance<span class="sc">$</span>distance_m <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">distHaversine</span>(time_distance[,<span class="dv">10</span><span class="sc">:</span><span class="dv">11</span>], time_distance[,<span class="dv">12</span><span class="sc">:</span><span class="dv">13</span>]))</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>time_distance<span class="sc">$</span>distance_per_minute <span class="ot">&lt;-</span> (time_distance<span class="sc">$</span>distance_m <span class="sc">/</span> time_distance<span class="sc">$</span>riding_time)</span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(time_distance<span class="sc">$</span>distance_per_minute)</span></code></pre></div>
<pre><code>## [1]  4.310078  1.379845  2.100775  2.100775 21.093023  3.558140</code></pre>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(time_distance<span class="sc">$</span>distance_m)</span></code></pre></div>
<pre><code>## [1]  556  178  271  271 2721  459</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>subset_casual <span class="ot">&lt;-</span><span class="fu">subset</span>(time_distance, member_casual <span class="sc">==</span> <span class="st">&quot;casual&quot;</span>) </span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(subset_casual<span class="sc">$</span>distance_m)</span></code></pre></div>
<pre><code>## [1] 1602.591</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>subset_member <span class="ot">&lt;-</span> <span class="fu">subset</span>(time_distance, member_casual <span class="sc">==</span> <span class="st">&quot;member&quot;</span>) </span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(subset_member<span class="sc">$</span>distance_m)</span></code></pre></div>
<pre><code>## [1] 1458.779</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(subset_casual<span class="sc">$</span>distance_m)<span class="sc">/</span><span class="fu">mean</span>(subset_member<span class="sc">$</span>distance_m)<span class="sc">*</span><span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 109.8584</code></pre>
<ul>
<li>Casuals ride <strong>9%</strong> more on an average ride.</li>
</ul>
<p><br></p>
</div>
<div id="distancetime-casuals-vs.-members" class="section level4">
<h4><strong>2.4.2 Distance/Time Casuals vs. Members</strong></h4>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co">#correlate distance and Casual status Box</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>time_distance_casual <span class="ot">&lt;-</span> <span class="fu">subset</span>(time_distance, member_casual <span class="sc">==</span> <span class="st">&quot;casual&quot;</span>)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>casual <span class="ot">&lt;-</span> <span class="fu">mean</span>(time_distance_casual<span class="sc">$</span>distance_per_minute)</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(time_distance_casual, <span class="fu">aes</span>(distance_per_minute)) <span class="sc">+</span></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Casuals&quot;</span>)</span></code></pre></div>
<p><img src="Detailed-Report_files/figure-html/correlate%20distance%20and%20Casual%20status%20Box-1.png" width="672" /></p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co">#correlate distance and Casual status Hist</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(time_distance_casual, <span class="fu">aes</span>(<span class="at">x =</span> distance_per_minute)) <span class="sc">+</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Casuals&quot;</span>)</span></code></pre></div>
<p><img src="Detailed-Report_files/figure-html/correlate%20distance%20and%20Casual%20status%20Hist-1.png" width="672" /></p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co">#correlate distance and Member status box</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>time_distance_member <span class="ot">&lt;-</span> <span class="fu">subset</span>(time_distance, member_casual <span class="sc">==</span> <span class="st">&quot;member&quot;</span>)</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>member <span class="ot">&lt;-</span> <span class="fu">mean</span>(time_distance_member<span class="sc">$</span>distance_per_minute)</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(time_distance_member, <span class="fu">aes</span>(<span class="at">x =</span> distance_per_minute)) <span class="sc">+</span></span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Members&quot;</span>)</span></code></pre></div>
<p><img src="Detailed-Report_files/figure-html/correlate%20distance%20and%20Member%20status%20box-1.png" width="672" /></p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co">#correlate distance and Member status Hist</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(time_distance_member, <span class="fu">aes</span>(<span class="at">x =</span> distance_per_minute)) <span class="sc">+</span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Members&quot;</span>)</span></code></pre></div>
<p><img src="Detailed-Report_files/figure-html/correlate%20distance%20and%20Member%20status%20Hist-1.png" width="672" /></p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>(member <span class="sc">/</span> casual) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 131.4174</code></pre>
<ul>
<li>Members ride 31.42% faster per minute on average.</li>
<li>Are they sportier ?</li>
</ul>
<p><br></p>
</div>
<div id="are-members-sportier-than-casual-riders" class="section level4">
<h4><strong>2.4.2.1 Are Members Sportier than Casual Riders</strong></h4>
<ul>
<li><p>Before we take a quick Conclusion we want to find out what influenced the location has on the traveled distance since we assumed a very simplistic model here. Using the DF from the chapter <strong>Time</strong>.</p></li>
<li><p>We compare the averages of the 212 stations we explored before for each member and casuals to avoid bias from non relevant locations (ruling out differences in traffic and routes).</p></li>
</ul>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co">#creating empty vectors</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>mean_list_distance_casual <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>mean_list_distance_member <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>mean_list_distance <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a><span class="co"># loop to build the means under each circumstance for distance/minute</span></span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> most_casual_riders){</span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a>mean_list_distance_casual <span class="ot">&lt;-</span> <span class="fu">append</span>(mean_list_distance_casual, <span class="fu">mean</span>(<span class="fu">subset</span>(time_distance_casual, start_station_id <span class="sc">==</span> i)<span class="sc">$</span>distance_per_minute))</span>
<span id="cb88-10"><a href="#cb88-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-11"><a href="#cb88-11" aria-hidden="true" tabindex="-1"></a>mean_list_distance_member <span class="ot">&lt;-</span> <span class="fu">append</span>(mean_list_distance_member, <span class="fu">mean</span>(<span class="fu">subset</span>(time_distance_member, start_station_id <span class="sc">==</span> i)<span class="sc">$</span>distance_per_minute))</span>
<span id="cb88-12"><a href="#cb88-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-13"><a href="#cb88-13" aria-hidden="true" tabindex="-1"></a>mean_list_distance <span class="ot">&lt;-</span> <span class="fu">append</span>(mean_list_distance, <span class="fu">mean</span>(<span class="fu">subset</span>(time_distance, start_station_id <span class="sc">==</span> i)<span class="sc">$</span>distance_per_minute))</span>
<span id="cb88-14"><a href="#cb88-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb88-15"><a href="#cb88-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-16"><a href="#cb88-16" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(mean_list_distance_member <span class="sc">/</span> mean_list_distance_casual)<span class="sc">*</span><span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 132.4597</code></pre>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co">#bind average distance per minute as column to the Dataframe</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>mean_casual_station <span class="ot">&lt;-</span> <span class="fu">cbind</span>(mean_casual_station, <span class="at">mean_distance_minute =</span> <span class="fu">c</span>(mean_list_distance))</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a><span class="co">#linear model 1: How perc_casual is explained by mean_distance_minute + mean_riding_time</span></span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(perc_casual<span class="sc">~</span>mean_distance_minute <span class="sc">+</span> mean_riding_time, <span class="at">data=</span>mean_casual_station))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = perc_casual ~ mean_distance_minute + mean_riding_time, 
##     data = mean_casual_station)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -23.4215  -3.3233   0.0786   3.6350  18.9525 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          14.690509   3.428868   4.284  2.8e-05 ***
## mean_distance_minute  0.007823   0.017314   0.452    0.652    
## mean_riding_time      1.660919   0.100790  16.479  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.387 on 209 degrees of freedom
## Multiple R-squared:  0.6643, Adjusted R-squared:  0.6611 
## F-statistic: 206.8 on 2 and 209 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co">#linear model 2: How mean_distance_minute is explained by mean_riding_time</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(mean_distance_minute <span class="sc">~</span> mean_riding_time, <span class="at">data=</span>mean_casual_station))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mean_distance_minute ~ mean_riding_time, data = mean_casual_station)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -98.468 -16.827  -4.711  16.505  66.936 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      179.3349     5.7984   30.93   &lt;2e-16 ***
## mean_riding_time  -3.5159     0.3202  -10.98   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 25.45 on 210 degrees of freedom
## Multiple R-squared:  0.3648, Adjusted R-squared:  0.3618 
## F-statistic: 120.6 on 1 and 210 DF,  p-value: &lt; 2.2e-16</code></pre>
<ul>
<li><p>The Mean for each station suggests that the members ride on average <strong>32.45%</strong> faster than casual riders, which suggests that the starting station has no significant influence on the Speed.</p></li>
<li><p>The Linear model suggests that the distance_minute is not significant when we add it to the linear model from chapter 3 which is why the linear model does not explain more with adding the variable of <strong>mean_distance_time</strong> (R^2 = 66.11%). Also suggested by the p value 0.652 &gt; 0.05.</p></li>
<li><p><strong>Result:</strong> Members are not significantly sportier than casual riders in a linear model</p></li>
<li><p><strong>Next step:</strong> Examine the exact relationship between mean distance and riding time to confirm the Result.</p></li>
</ul>
<p><br></p>
</div>
<div id="correlation-distanceminute-vs.-casualsstation" class="section level4">
<h4><strong>2.4.2.2 Correlation: distance/minute Vs. %casuals/station</strong></h4>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># trend Distance_m vs. casuals per station</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>trend_casual_distance <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(mean_casual_station, <span class="fu">aes</span>(<span class="at">x =</span> mean_riding_time, <span class="at">y =</span>mean_distance_minute )) <span class="sc">+</span></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Regression mean_riding_time | mean_distance&quot;</span>)</span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a>trend_casual_distance <span class="ot">&lt;-</span> trend_casual_distance <span class="sc">+</span> <span class="fu">expand_limits</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">y =</span> <span class="dv">0</span>)</span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a>trend_casual_distance <span class="ot">&lt;-</span> trend_casual_distance <span class="sc">+</span> <span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)) <span class="sc">+</span> <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>))</span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-10"><a href="#cb94-10" aria-hidden="true" tabindex="-1"></a>trend_casual_distance</span></code></pre></div>
<p><img src="Detailed-Report_files/figure-html/Distance_m%20vs.%20casuals%20per%20station-1.png" width="672" /></p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co">#second trend graph for comparison</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>trend_casual_distance <span class="ot">&lt;-</span><span class="fu">ggplot</span>(mean_casual_station, <span class="fu">aes</span>(<span class="at">x =</span> perc_casual, <span class="at">y =</span> mean_distance_minute)) <span class="sc">+</span></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Regression perc_casual | mean_distance&quot;</span>)</span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a>trend_casual_distance <span class="ot">&lt;-</span> trend_casual_distance <span class="sc">+</span> <span class="fu">expand_limits</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">y =</span> <span class="dv">0</span>)</span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-8"><a href="#cb95-8" aria-hidden="true" tabindex="-1"></a>trend_casual_distance <span class="ot">&lt;-</span> trend_casual_distance <span class="sc">+</span> <span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)) <span class="sc">+</span> <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>))</span>
<span id="cb95-9"><a href="#cb95-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-10"><a href="#cb95-10" aria-hidden="true" tabindex="-1"></a>trend_casual_distance</span></code></pre></div>
<p><img src="Detailed-Report_files/figure-html/trend_distance%202-1.png" width="672" /></p>
<ul>
<li><p>As a linear Model does not represent our Data fully we need to take a look at the Trend in the Graphs above.</p></li>
<li><p>The Scattering of the mean_distance in comparison to the mean_riding_time seems very similar.</p></li>
<li><p>The Trend line suggests a somewhat linear relationship between the two but at the edges the linearity is switching over to a logarithmic relationship.</p></li>
<li><p>In the end it is not Clear if the members are sportier the Data can not support the Claim since the distance/time does not have a significant influence on the membership.</p></li>
</ul>
<p><br></p>
</div>
</div>
<div id="further-exploration-with-tableau" class="section level3">
<h3><strong>2.5 Further exploration with Tableau</strong></h3>
<p><a href="https://public.tableau.com/app/profile/jonas112520/viz/CaseStudyCyclisticDashboard/DasboardCyclisticCaseStudy">View in Tableau Dashboard</a></p>
<div id="location" class="section level4">
<h4><strong>2.5.1 Location</strong></h4>
<ul>
<li><p>From Chapter 1.2 we found out what Stations are most important to look at but we can not see if there are geographical differences just by looking at the raw Data.</p></li>
<li><p>Data: counts of members and casuals in all locations</p></li>
</ul>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create Dataframe for Export CSV into Tableau</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>total_station_location <span class="ot">&lt;-</span> <span class="fu">count</span>(<span class="fu">group_by</span>(data_all,start_station_id), <span class="at">member_casual=</span>member_casual)</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>location_lat_lng <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(start_lat <span class="sc">~</span> start_station_id, <span class="at">data=</span>data_all, <span class="at">FUN=</span>mean)</span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a>location_lat_lng<span class="sc">$</span>start_lng <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(start_lng <span class="sc">~</span> start_station_id, <span class="at">data=</span>data_all, <span class="at">FUN=</span>mean)<span class="sc">$</span>start_lng</span>
<span id="cb96-7"><a href="#cb96-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-8"><a href="#cb96-8" aria-hidden="true" tabindex="-1"></a>location<span class="ot">&lt;-</span> <span class="fu">merge</span>(total_station_location, location_lat_lng, <span class="at">by.x =</span> <span class="dv">1</span>, <span class="at">by.y =</span> <span class="dv">1</span>, <span class="at">all.x =</span> <span class="cn">TRUE</span>)</span>
<span id="cb96-9"><a href="#cb96-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-10"><a href="#cb96-10" aria-hidden="true" tabindex="-1"></a>location_casual <span class="ot">&lt;-</span> total_station_location <span class="sc">%&gt;%</span></span>
<span id="cb96-11"><a href="#cb96-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(. , member_casual <span class="sc">==</span> <span class="st">&quot;casual&quot;</span>)</span>
<span id="cb96-12"><a href="#cb96-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-13"><a href="#cb96-13" aria-hidden="true" tabindex="-1"></a>location_member <span class="ot">&lt;-</span> total_station_location <span class="sc">%&gt;%</span></span>
<span id="cb96-14"><a href="#cb96-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(. , member_casual <span class="sc">==</span> <span class="st">&quot;member&quot;</span>)</span>
<span id="cb96-15"><a href="#cb96-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-16"><a href="#cb96-16" aria-hidden="true" tabindex="-1"></a>difference_riders <span class="ot">&lt;-</span><span class="fu">merge</span>(location_casual, location_member, <span class="at">by.x =</span> <span class="dv">1</span>, <span class="at">by.y =</span> <span class="dv">1</span>, <span class="at">all.x =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb96-17"><a href="#cb96-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">difference_casual_member =</span> n.x <span class="sc">-</span> n.y)</span>
<span id="cb96-18"><a href="#cb96-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-19"><a href="#cb96-19" aria-hidden="true" tabindex="-1"></a>location <span class="ot">&lt;-</span> <span class="fu">merge</span>(location, <span class="fu">select</span>(difference_riders, start_station_id, difference_casual_member), <span class="at">by.x =</span> <span class="dv">1</span>, <span class="at">by.y =</span> <span class="dv">1</span>, <span class="at">all.x =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<ul>
<li>Plot the dataset in Tableau and get the Following Graphics as results:</li>
</ul>
<p><img src="Detailed-Report_files/figure-html/Distribution%20Casuals+members-2.png" width="90%" /><img src="Detailed-Report_files/figure-html/Distribution%20Casual+members%202.png" width="90%" /></p>
<ul>
<li>Most casual riders use the service near the coastline of Chicago</li>
<li>Most members use the service in the city</li>
</ul>
<p><br></p>
</div>
<div id="compare-seasonal-time-differences" class="section level4">
<h4><strong>2.5.2 Compare Seasonal Time differences</strong></h4>
<ul>
<li>In addition to Chapter 2.3 (Time) seasonal Data is explored in this chapter</li>
</ul>
<div id="examine-the-monthly-frequency-of-bike-usage-among-casuals-vs.-members" class="section level5">
<h5><strong>2.5.2.1 Examine the monthly frequency of bike usage among casuals vs. members:</strong></h5>
<p><img src="Detailed-Report_files/figure-html/Frequency%20Member%20and%20Casuals%20Bike%20Usage%20per%20Month.png" width="90%" /></p>
<ul>
<li><p>Members use the service a lot more than casuals in the winter months</p></li>
<li><p>During june to august casuals use the service a lot more frequent</p></li>
</ul>
<p><br></p>
</div>
<div id="examine-the-usage-per-day-throughout-the-week" class="section level5">
<h5><strong>2.5.2.2 Examine the usage per day throughout the week:</strong></h5>
<p><img src="Detailed-Report_files/figure-html/Usage%20of%20Bikes%20per%20Weekday-2.png" width="90%" /></p>
<ul>
<li><p>Members use the bike more frequent during monday-friday</p></li>
<li><p>Members still are pretty even on bike usage throughout the week</p></li>
<li><p>Casuals use the bike service a lot more frequent during the weekend</p></li>
</ul>
<p><br></p>
</div>
<div id="examine-the-usage-per-hour-throughout-the-day" class="section level5">
<h5><strong>2.5.2.3 Examine the Usage per hour throughout the Day:</strong></h5>
<p><img src="Detailed-Report_files/figure-html/Usage%20of%20Bikes%20per%20Daytime.png" width="90%" /></p>
<ul>
<li><p>Casuals usage throughout the day is steadily increasing from 5 am to 5 pm. The usage peaks at around 5 pm and is then again steadily decreasing til 5am.</p></li>
<li><p>Members usage throughout the day is rapidly increasing from 4 am to around 7 am. From 7 am the usage decreases again til 10 am. From there on the increase is steady until 2pm, where the increase becomes rapid again and peaks at 5 pm. From 5 pm the decrease is rapid until 4 am.</p></li>
</ul>
<p><br></p>
</div>
</div>
</div>
</div>
<div id="summary" class="section level2">
<h2><strong>3. Summary</strong></h2>
<ol style="list-style-type: decimal">
<li><p>38% of the classic_bikes, 44.55% of the electric_bikes and 100% of the docked bikes are used by casual members. (Chapter 2.1)</p></li>
<li><p>There are 212 Stations which are most relevant to draw Conclusions on casuals and 209 for members. (Chapter 2.2)</p></li>
<li><p>Casuals ride longer than members on average. (Chapter 2.3)</p></li>
<li><p>With longer riding time the distance/minute steadily decreases, therefore casuals ride a lot less distance/minute than members. (Chapter 2.4)</p></li>
<li><p>Members are not significantly sportier than casuals. (Chapter 2.4)</p></li>
<li><p>Casuals are a lot more likely to ride along the Coastline while members ride in the city. (Chapter 2.5.1 Location)</p></li>
<li><p>Members ride a lot more during the winter months, while casuals like to ride more during june to august. (Chapter 2.5.2.1 Usage per Month)</p></li>
<li><p>Casuals ride more on Weekends than members. (Chapter 2.5.2.2 Usage per Weekday)</p></li>
<li><p>Casuals ride the most during afternoons, while Members ride preferably during rush hours in the morning and afternoon. (Chapter 2.5.2.3 Usage per Daytime)</p></li>
</ol>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
